### ISSUE TITLE
Come back with an estimation on how long it would take to improve the tools so we can filter Firefox-only code from gecko-dev repo

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#100]
Come back with an estimation on how long it would take to improve the tools so we can filter Firefox-only code from gecko-dev repo

**Comment by jgbarah** [comment]
Can we assume everything in the `gecko-dev` repo is project Gecko, except for directory `browser`, which is project Firefox? In particular, I was reading this comment, by Myk Melez, which suggests that maybe for project Firefox we should have some more directories into account:

> As noted in the description for the Firefox module, the primary source directory for "just Firefox" code in gecko-dev is browser/. Almost everything else is a part of Gecko, although the toolkit/ and chrome/ directories are a part of the Toolkit module, which is not entirely independent of Firefox (and shares a module owner and peers).

**Comment by nukeador** [comment]
For the toolkit/ and chrome/ forlders we don't a good way to know which is Firefox-only and which is Gecko-only so we are assuming it's part of Gecko contributions.

@mykmelez we didn't get any other tips to separate the code there right?

**Comment by mykmelez** [comment]
> For the toolkit/ and chrome/ forlders we don't a good way to know which is Firefox-only and which is Gecko-only so we are assuming it's part of Gecko contributions.

In the absence of more precise distinctions between the various directories in toolkit/, I would actually count toolkit/ as Firefox, because its [module's peers](https://wiki.mozilla.org/Modules/All#Toolkit) are identical to the [Firefox module's peers](https://wiki.mozilla.org/Modules/All#Firefox), and its code is more "frontendy" than "backendy".

However, I still think @Mossop is the better person to answer this question, as he is the module owner for both modules.

> @mykmelez we didn't get any other tips to separate the code there right?

Correct, although here are a couple of possible heuristics:

* count directories which contain predominantly C++ code as Gecko, the rest as Firefox.
* count directories whose primary contributors' primary contributions outside toolkit/ are to Gecko code as Gecko, the rest as Firefox.

**Comment by jgbarah** [comment]
>>    @mykmelez we didn't get any other tips to separate the code there right?
>
> Correct, although here are a couple of possible heuristics:
>
> *   count directories which contain predominantly C++ code as Gecko, the rest as Firefox.
> *  count directories whose primary contributors' primary contributions outside toolkit/ are to Gecko code as Gecko, the rest as Firefox.

Both heuristics are tricky in the timeframe we hace, so I will stick to using directories. We can revisit this later if you're interested.

So far, I understand then that `browser`, `toolkit` and `chrome` directories are project Firefox, the rest is Gecko.

Any hint on what to do with commits touching files in both parts? (Firefox and Gecko). For now, I'm planning to split in like two commits, one for each "part".

**Comment by jgbarah** [comment]
Finally, decided on:

* Filter by directoriy. if directory is `browser`, `toolkit` or `chrome`, consider project Firefox. If any other, consider Gecko.
* I a commit touches files both in Firefox and Gecko, consider the commit for the project with more files touched (simple, but seems to work reasonably well, from manual inspection).

Results: 

* For the last two years: Firefox ~13,6K commits, Gecko ~115.5K commits
* For the whole history of the repo: Firefox ~70.2K commits, ~531.7K commits

Screenshot with commits per month during the last 10 years. Ignore since Jan 2017, please. Does the rest of the evolution make sense?

![selection_207](https://user-images.githubusercontent.com/1039693/26866687-9756fc2e-4b62-11e7-892c-1563e12cb694.png)

**Comment by alpgarcia** [comment]
I just updated Community notebook to use new data:
Community metrics updated applying this: https://github.com/Bitergia/mozilla-contribution-analysis/blob/master/data-analysis/rc1/html/Community.html

**Comment by nukeador** [comment]
I'll check about the numbers, let's assume for now these are correct.

**Comment by nukeador** [comment]
From yesterday's meeting, this is ready and implemented.

**Comment by alpgarcia** [comment]
After checking data we realized some commits associated to Firefox are also present (and associated to Gecko) in **gecko-projects** and **universal-search-gecko-dev repos**.

We decided after talking with @nukeador  to remove both repos from our indexes as probably they are only introducing noise to the analysis.
