### ISSUE TITLE
Github external org tool is ready and data gathered

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#109]
Specs: https://docs.google.com/document/d/1xLEmiU21wotdBcB7An6dyf40dluUn9BvvbTduzWSFpA/edit#

**Comment by nukeador** [comment]
Bitergia will come back next week with time estimations

**Comment by jgbarah** [comment]
I think you got the estimations via email. Meanwhile, some comments:

* For now, we're focused on git repos in GitHub, since that seems to be more complete than issues / pull requests.

* We're limited by the GitHub API, to about 30K commits/hour. Likely this could be enough to get at least the activity of most active non-employees.

* There is an interesting problem: forks. How should we consider commits in several repositories? If we just count them as separate commits, the activity of a developer can be overestimated by a large amount. If not, we need to know to which repo to "assign" the commit, which would be (maybe) hard. We're researching if commits in GitHub forks (those forked using GitHub itself) are reported by the API as "repeated" commits. That would be a real problem, since a repo forked eg 1,000 times would have 1,000 copies of each of its commits. (but likely this is not the case, and the GH API is masking this).

**Comment by nukeador** [comment]
The problem about overestimating I guess is due the forks right? Then, yes, we should probably ignore forks (I don't know if you have a way to detect same commit under different repos)

**Comment by jgbarah** [comment]
> Then, yes, we should probably ignore forks (I don't know if you have a way to detect same commit under different repos)

No, this is a fundamental problem. We don't have an easy way of ignoring forks not produced through the GH interface (manual forks), and if we had, I don't know of a way for telling apart which one is the "original" and which one is the "copy.

**Comment by nukeador** [comment]
I see, what would be your suggestion to have the minimum deviation and data result to be useful?

**Comment by jgbarah** [comment]
We're working on that. Maybe the forks of the "main" repository are not relevant (and can be easily discarded). And likely the issues / pull requests results are more conclusive (assuming people use GH for that, which is not always the case). I just wanted to stress that the data is maybe not going to be as useful as it appeared at first glance.

**Comment by jgbarah** [comment]
Some more feedback, after we got some preliminary results for a first run. We get a listing of commits and organizations, but at least in some cases, it has some problems from the point of view of learning where people works. The issue is that people fork git repos manually, and that means that developers appear as active in those repos. But they really didn't work in them: they were forked by somebody else, and they never contributed directly to the new repo.

OTOH, it seems clear that when the fork was done via the GH interface, commits in forks are not reported when asking for activity to the GH search API, which is good news.

**Comment by nukeador** [comment]
But even if they fork repos manually, commits are not under their names unless they commit something there I assume.

**Comment by jgbarah** [comment]
> But even if they fork repos manually, commits are not under their names unless they commit something there I assume.

Nope. The fork includes all commits, with the corresponding commit record, which includes the name of the author. Therefore, the person appears as a committer in the fork.

**Comment by acs** [comment]
Summary of the work done and already available in the Activity Dashboard:


1. All the data is collected from https://mozilla-test.biterg.io/data
2. The list of commit authors for Community (Unknown + Mozilla Reps) is extracted from Kibana for the last year (starting from 13rd July), including for each author her main project in Mozilla, the list of all projects in which she has contributed and the number of commits for the main project.
3. With the above list, the uuids of the authors are used to find the github username using SortingHat information.
4. From the github usernames list extracted in the previous step, the GitHub Search API is used to collect all tickets and pull requests in which the github usernames were involved in all repositories in GitHub for the full history. These issues (raw data) are loaded in Elasticsearch (>800K).
5. The issues data is processed and using the raw data for them, and the information collected in the second step, an enriched index is generated including for each issue the username involved, her main mozilla project and commits, the list of her mozilla projects, the github organization and repository for the issue, the date in which the issue was created and if the issue is a github ticket or a github pull request.
6. With the enriched index the Activity Dashboard is created.

**Comment by nukeador** [comment]
Thanks for the update @acs Great work so far! :-)

About (2), how bigger would be the sample if we include Mozilla contributors in the last 2-3 years?

Also, we talked yesterday with @jgbarah that maybe it would be interesting to be able to filter in/out based on number of commits on our repos, so this way we can exclude people that maybe are too casual and just contributed once or twice.

**Comment by nukeador** [comment]
Is it doable to have this data from Mozilla Contributors (3 years back) so it's usaed by #105 this week?

**Comment by acs** [comment]
@nukeador I would try to complete all process for 3 years back. Once it is ready I will update this ticket and we can evaluate if it is ready!

**Comment by acs** [comment]
@nukeador enriched index updated with the github users which done commits last 3 years. In the activity dashboard you can check the data. 4529 users tracked this time.

**Comment by nukeador** [comment]
I think we can close this one, since the tool is working correctly and it's now being used for insights at #105

**Comment by nukeador** [comment]
BTW, great work, this is going to get us a lot of answers now and in the coming weeks ;-)

**Comment by acs** [comment]
@nukeador it is great that the data and insights provides you answers! It is the final goal of all the stack! I will be more than happy to continue in the process next weeks!
