### ISSUE TITLE
Discussion on the repositories/project grouping

### ISSUE THREAD

**Issue by dicortazar** [mozilla/participation-metrics-org#118]
This task aims at starting a discussion about the needs to be covered when grouping repositories and projects information.

At Bitergia a specific version of the spreadsheet was used due to some missing repositories in the general spreadsheet.

We need to work in the following actions:
* Update the official spreadsheet with missing repositories (those used in mozilla-test).
* Discuss if that official spreadsheet is going to be the central place for updates (and those changes should be done through the same people, having them as gatekeepers).
* Check how to add specific information for specific repositories. As an example, in the Gecko repository we need to have a difference between Gecko and Firefox.

This ticket may affect @sanacl . CC @jgbarah .

**Comment by nukeador** [comment]
Instead of going to the solutions I would like to better shape the problem statement:

We need a central place under Mozilla's github repo where kibana can fetch:

* All sources of data and their type (git, github, bugzilla, discourse...)
* Each source should also have a project assigned (for grouping)
* There is an easy (webby?) way for both Bitergia and Mozilla to modify this list.
* We just don't need to maintain different pieces for this (single source of truth)

@hmitsch Would you agree on this?

**Comment by dicortazar** [comment]
A bit of extra context:

* Grimoirelab toolchain needs a file where all of this info is provided. We already support the spreadsheet and we have our own file format (as far as I remember). For us centralizing all of this info would be the best option.
* In the case of mozilla-test, that info is now being extracted from a local spreadsheet that is a copy from the one in GDocs.

**Comment by nukeador** [comment]
My proposal:

* Use the central github repo (the one we are working to have under parsys)
* Have a csv file per source type (git, bugzilla, mailing list, reps, discourse...)
* These files will include the list of sources (urls) and the project group they belong to.

This is not perfect but would allow kibana to fetch these files and transform into a projects.json or whatever it needs in order to know which sources to fetch and their project.

Ideally in the future kibana should have a UI to be able to modify these lists directly from there (instead of github).

**Comment by dicortazar** [comment]
@nukeador the following is an example of the JSON file we're using when building dashboards.

Our ideal situation would be to use this and with this format:
* https://github.com/Bitergia/projects-mozilla/blob/master/projects.json

**Comment by nukeador** [comment]
Well a json is way more difficult to edit by non-technical people, even for me it's difficult to edit when you don't see each source in one line.

I suspect we can have csv files integrated into a json automatically to balance ease of use from humans vs what kibana understands ;-)

**Comment by hmitsch** [comment]
Done, as per https://github.com/Bitergia/projects-mozilla/pull/3/files we use the Google Spreadsheet.
