### ISSUE TITLE
Upgrade Kibana and Elasticsearch (FEB 2018 Vulnerability Assessment)

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#156]
Source: [Bug 1434962](https://bugzilla.mozilla.org/show_bug.cgi?id=1434962)

From @sanacl:
> We are working these days to define whether we will upgrade to 5.6 or directly go to 6.x.

**Comment by hmitsch** [comment]
Evaluation for upgrades is ongoing on Bitergia side. We plan to review this in the beginning of Q2.

**Comment by sanacl** [comment]
Our team is working in the migration. The elastic release chosen (this could change a little bit) is 6.1

**Comment by sanacl** [comment]
Hi @johngian ,
in order to start preparing the migration. Can u please confirm the way to "upgrade" a elasticsearch server in Amazon is by moving the content to another cluster? If we can just upgrade the cluster to 6.1 (elasticsearch supports that) that would be nice.

**Comment by sanacl** [comment]
@johngian ping. Can u please answer the question above? :)

**Comment by sanacl** [comment]
Thanks for the feedback @johngian . I'll talk to the team to @acs to discuss the better approach. Having a look at the link you shared I read: 

> "Elasticsearch 2.3 snapshots are not compatible with 6.x. To migrate your data directly from 2.3 to 6.x, you must manually recreate your indices in the new domain. "

**Comment by sanacl** [comment]
Hey @johngian, I've just remembered we are already running ES 5.1.0 :smile: .

According to the schedule (and it is a work in progress) we would be able to jump to 6.1.0 around first week of June. So we would need this extra server to migrate the data, does this schedule work for you guys? @hmitsch @johngian (please keep in mind these dates are not fixed yet)

**Comment by hmitsch** [comment]
A note on the timeline:

Based on today's understanding we probably want to upgrade ElasticSearch in late May/**early June**.

**Comment by johngian** [comment]
I just verified with @sanacl that we are indeed using the ES 5.x cluster.
Thanks @sanacl for the clarification.

**Comment by sanacl** [comment]
Hi @hmitsch @johngian, it is time to start with the dashboard upgrade. This is what we need in order to start moving data and deploying the new Kibiter:
* a) Elasticsearch 6.1.0 instance
* b) new VM node with latest Debian stable (same setup we are using in the current VM)

This is my proposal for the migration plan:
- 1) once we find an agreement about the date, the current dashboard will be frozen until the new one is fully operational, by frozen I mean no new data will be published.
- 2) we will migrate data from our current ES to the new one, it will take some days as we have to copy the data and change the mapping (and check it is working)
- 3) the new VM will be used to deploy a web server (nginx) + proxy + Kibiter (Kibana fork). It would be great to get a temporary DNS such as https://analytics2.mozilla.community to check everything is working before switching the servers
- 4) once we are sure everything is ready, I would like to keep the two VMs to split the services. One would keep the web server + Kibiter, the other would update the ES data. This way we don't kill the service if the software that updates the data have memory leaks. When we reach this step, the memory requirements should be revisited as we may not need all the resources deployed (in terms of memory).
- 5) last step will be to decommission the old ES server

**Comment by sanacl** [comment]
It seems getting a) is impossible according to the list of versions provided by AWS. See https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/what-is-amazon-elasticsearch-service.html#aes-choosing-version

We're discussing the best approach here. We can talk about this in our next meeting on Thursday.

**Comment by johngian** [comment]
Next steps regarding infrastructure migration

* Figure out if aws hosted ES allows exporting snapshots to s3
* (If feasible) Export current ES domain to s3
* Spin off new stack which involves
  * Set up new ELB to terminate SSL
  * Set up new VMs for
    * nginx, proxy, kibiter
    * rest of memory hungry software
  * Set up new ES domain using the new ES version
* Terminate temporary endpoint to ELB with new temp dns
* If migration works out correctly failover to new stack
* Kill all instances

**Comment by sanacl** [comment]
Hi @johngian and @hmitsch,
we've been testing our current release with the services provided by AWS (ES 6.2.0) and we confirm we can proceed with the data migration+upgrade.

## Phase 0

There is a previous step before having the new infrastructure. This first step will need to reindex most of the current indexes to update the mapping we are using, to make possible the jump to ES 6.x. We can start with this step between Tuesday/Wednesday. In order to do this we will stop the data collection, but it could be restarted when the reindex operations are done (if we can't proceed with next phase immediately). 

## Phase 1

When the indexes get ready to be placed in a ES 6.x we will need the new servers. The critical step in this second phase is to get the indexes up&running in the ES 6.2. If AWS makes possible to import snapshots from one cluster to another, these operation will be short. If not, we'll move the data (300GB) from the old ES to the new one (version 6.2).

## Phase 2

Once data is migrated and available under a ES 6.2 version, we can start the third phase which will be deploying both the web interface (in one VM) and the "hungry" software in another. Both VMs will need direct access to the ES server. 

## Summary

As @johngian wrote above, the layout would be:
* 2 VMs for:
** Nginx, Proxy, Kibiter, Hatstall (for this one we would need a domain accessible from internet)
** GrimoreLab data collectors
* the SQL server, which won't need to be modified
* ES instance

The current dashboard will be available all the time but it could be slower due to the load we add to the server. When the new infra is ready, we would sync with @johngian to switch the DNS.

---

Please let me know if you agree with the plan and whether you need more information.

**Comment by sanacl** [comment]
Hi @hmitsch @johngian ,
we can start moving data to the new ES. As soon as data is imported there, our latest version will start producing fresh enriched items to be shown on Kibana.

@johngian we need to create a snapshot of the indexes below and import it in the new cluster. If we can import an automatic snapshot done today (Thursday 11th) it is also ok. The only limitation is the list of indexes (the rest of them are not prepared to be imported in 6.2.0). Can u do this @johngian? I can do it if you allow the s3 bucket to be accessible from the new ES cluster. In order to share with me the credentials the easiest way is writing them in a file in one of the current VMs.

Lists of indexes to be imported into ES 6.2.0:
```
bugzillarest_mozilla_180411
crates_mozilla_171205_1
discourse_mozilla_180410
github_mozilla_180322
git_mozilla_180206
mediawiki_mozilla_161010
meetup_mozilla_180322
mozillaclub_180416
nntp_mozilla_180416
remo_activities_mozilla_180723
remo_mozilla_180924
slack_mozilla_180301
stackexchange_mozilla_180322
supybot_mozilla_171106
twitter_mozilla_180628b
```

Overall status:
* Phase 0 is close to be over (80% done, we need to backup some data just in case)
* Phase 1 is in progress

**Comment by sanacl** [comment]
Hi folks,
this is the status.

* Phase 0: 90% done, we just need to backup a couple of data sets
* Phase 1: 80% done, yesterday night we started copying data directly using elasticdump. One of the indexes is not copied yet because of memory errors of this tool. We've changed the parameters to do that copy without the error. WIP.
* Phase 2: 0% done, to be started

**Comment by hmitsch** [comment]
Thanks for live-blogging!

-Henrik

**Comment by hmitsch** [comment]
Currently expecting to be done with the migration on Monday. 🎉

**Comment by sanacl** [comment]
Hi folks,
this is the status.

* Phase 0: done
* Phase 1: done
* Phase 2: the data analysis needs to update the data sources. This should be finished during today (Tuesday). In any case I've disable Meetup and NNTP and we still have the memory issue at #180. Luckily the dev team is already working on it and this time we can apply the fixes.

I'll need feedback from @johngian to setup the proxy and to reboot the data analysis node if our software goes crazy again. As soon as we have the data on the dashboard, I'll need from @hmitsch the green light to switch analytics.mozilla.community to the new service.

**Comment by sanacl** [comment]
Hi folks,
this is the status.

The dashboard is already available at https://analytics.mozilla.community but there is still some data to be refreshed:
* Git commits does not contain bot information so bots can not be filtered out. Data is being refreshed and will be fixed by tomorrow early morning
* Github issues does not contain bot information so bots can not be filtered out. Data is being refreshed and will be fixed by tomorrow early morning
* NNTP data is not updated due #180 which is not solved yet, data will be updated by next week
* Meetup data is not updated due #180 which is not solved yet, data will be updated by next week
* IRC data is not updated, it will be updated by next week

By next week I'll review everything once again to confirm we can decommission the old servers.

**Comment by sanacl** [comment]
Update:
* Git commits refreshed with data about bots.
* Github issues refreshed with data about bots.

To be refreshed:
* NNTP data is not updated due #180 which is not solved yet, data will be updated by next week
* Meetup data is not updated due #180 which is not solved yet, data will be updated by next week
* IRC data is not updated, it will be updated by next week

**Comment by hmitsch** [comment]
🎉 thanks a lot, @sanacl !

**Comment by sanacl** [comment]
Status:
* The following dashboards was not up&running until now. There is a small manual step to be done here and we were quite slow doing them. Sorry for this. The links are:
** Emerging Tech:
***  "Adoption": https://analytics.mozilla.community/app/kibana#/dashboard/EmTech-Adoption
***  "Development": https://analytics.mozilla.community/app/kibana#/dashboard/EmTech-Dev
***  "Social": https://analytics.mozilla.community/app/kibana#/dashboard/EmTech-Social
***  "Community": https://analytics.mozilla.community/app/kibana#/dashboard/EmTech-Community-Structure
* Tomorrow we can talk about the menu, I guess you'll want to have the same entry for Emerging Tech you had before

To be refreshed:
* NNTP data is not updated due #180 which is not solved yet, data will be updated by this week
* Meetup data is not updated due #180 which is not solved yet, data will be updated by this week
* IRC data is not updated, it will be updated by this week

If you agree @hmitsch as soon as IRC is updated we can close this ticket and keep working on the #180 to get NNTP and Meetup data updated.

**Comment by sanacl** [comment]
Hey folks,
the upgrade is done. Now it is time to work on #180 which is affected the data freshness as the process is still eating too much memory.

So, @johngian you can decommission the old VM and the old ES cluster.
