### ISSUE TITLE
Add Twitter to the Community Analytics Menu

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#161]
This request is related to one of the work items in the Q1/2018 SOWs.

We created a new tab in the Project Grouping sheet and added 3 Twitter hashtags.

Let's add this to the regular Menu to make it easily discoverable.

**Comment by sanacl** [comment]
Hey @hmitsch due to I'm pretty late with this I've just generated a set of data to allow u get an idea about the fields offered. The author_uuid are wrong, so please don't pay attention to them in this testing data set.

https://analytics.mozilla.community/edit/goto/460168ef26e80cf0759cb7dfecbcc12c

I have to talk with @acs to understand why we have more than 1 organization and more than 1 project with the setup I've just deployed. I'll keep u informed

**Comment by sanacl** [comment]
Dashboard available and linked from menu https://analytics.mozilla.community/app/kibana#/dashboard/Twitter

Some remarks:
- we have affiliation for some Mozillians, but the affiliation is not complete at all
- there is a bug in the username field, which is empty on the dashboard. I'm talking to the guys here to see why this is happening (we have the twitter username, but the field is showing a different name and I want to know why)

**Comment by sanacl** [comment]
The issue of empty names is related to the unified profile our identities database has for every contributor. The configuration applied was not taking into account Twitter, that is why when no other identity is found for a given contributor the unified name is empty on the dashboard. 

I've changed the setup and changes should be visible by this afternoon.

**Comment by hmitsch** [comment]
This is what it currently looks like:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/869692/37759314-86e4529a-2db3-11e8-9755-4bcdbf6319a8.png">


We expect this to be fixed later today.

**Comment by sanacl** [comment]
This is already solved. 

https://analytics.mozilla.community/goto/3a790fcaa6ea6e14201b3ac12bc8dfdb
