### ISSUE TITLE
As an Activate Program Manger I want to have a daily/weekly/monthly/quarterly view on the number of Activate Events in order to visualize them on the Main Activate Campaign Dashboard 

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#17]

**Comment by hmitsch** [comment]
**Data source:** Poll the Reps Portal for events from the "Activate campaign".

**Comment by sanacl** [comment]
I will confirm this is feasible asap

**Comment by hmitsch** [comment]
Requires https://github.com/mozilla/participation-metrics-org/issues/9, same as https://github.com/mozilla/participation-metrics-org/issues/18

**Comment by hmitsch** [comment]
Simplification: To keep "out of the box" Kibana functionality, we filter inside Kibana and NOT build a specific dashboard.

**Comment by brianking** [comment]
Poking around at https://analytics.mozilla.community I seem to be able to get this data.

I go to 'Reps2 Activities' and apply the following filters:

- Initiative: "MozActivate"
- A time filter using the drop down on the top right of the site

**So if I filter from 1-31 October I get 85 events**.

Question: Can I have this data presented on a separate 'MozActivate' dashboard on the site?

TODO: work with @akatsoulas to verify this data.

**Comment by jsmanrique** [comment]
@brianking you can get the short link for your specific query/filter. Use the top right "share" button (next to search box) and you can the short iframe our url to be used.

For your case I think it would be: 
https://analytics.mozilla.community:443/goto/79254ee778c153a5c064c123f33bd3bb

Instead of a fixed date range, I have used "latest 30 days" time filter, so each 1st day of the month you should have the activity of latest month
