### ISSUE TITLE
Update GitHub repo list + OSSN Organization (26 JUL 2018)

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#182]
Please 
* Update [GitHub repo list + project grouping](https://docs.google.com/spreadsheets/d/1xFrt9JZkZ6m8peasYaRfPO5kC1JDo-vDJJuYfMwcGqM/edit) (24 JUL 2018)
* Update the [OSSN Organization](https://github.com/mozilla/participation-metrics-identities/blob/master/OSSN-31-May-2018.csv) (26 JUL 2018)

**Comment by hmitsch** [comment]
cc @bacharakis

**Comment by hmitsch** [comment]
Hi @sanacl,

as mentioned in today's status call, could you please also take care of this request in the next few days?

Best regards,
   Henrik

**Comment by sanacl** [comment]
I've been reviewing the enrollment data for OSSN and I can not find data for the following entries: 33, 39, 44, 45, 48, 49, 67 and 68. This could be related to not having all the data from the issues and PRs yet. It is taking a lot due to API limitations.

**Comment by sanacl** [comment]
Finally we have Github data. Due to our recent software gets the reactions from Github, the API rate limitation is hitting us. We had to disable the reactions data to get the basic stuff (issues, PRs). In any case we have reactions data for some repos just in case you want a demo. In order to have all the reactions data we need to start a new data collection in parallel so we don't block anything.

Some data about the OSSN folks:
* https://analytics.mozilla.community/goto/56eb2eff466938c73a2a794b4551de6d
* https://analytics.mozilla.community/goto/91e433f0e3334fe4ba1b1ab81b9630b5

**Comment by hmitsch** [comment]
Closing issue. Thank you!
