### ISSUE TITLE
Update data collection software

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#19]

**Comment by sanacl** [comment]
The only data source that should be outdated tomorrow is the mailing lists. We were tracking Gmane but it is down since a couple of months. We are tracking most of the mailing lists so we can parse our mboxes. The software to speed up the generation of the dashboard (called mordred) wasn't finished yet. Should be finished during the week.

**Comment by hmitsch** [comment]
Let's take a "staggered approach": Make sure data for the last 30 days is available while processing the "complete data" (in some areas years of records) in the background.

**Comment by sanacl** [comment]
We won't be able to have several updates per data source until we get the https://github.com/mozilla/participation-metrics-org/issues/13

What we are about to finish is a stable method to get an update for everything every 24 hours.

**Comment by hmitsch** [comment]
Data loading issues were intensely analyzed and a lot of things were fixed. Currently, data imports are working.
