### ISSUE TITLE
(Deployment) SOW Acceptance Test: Deduplication validation

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#65]

**Comment by hmitsch** [comment]
<img width="654" alt="image" src="https://cloud.githubusercontent.com/assets/869692/20001939/9e9b8e74-a27e-11e6-954a-1640fdee9f67.png">

**Comment by sanacl** [comment]
This is the information our system gathered about you Henrik
```
unique identity 0f6da1096c5b9ecba9c45e4637f3af6a2cfa7529

Profile:
    * Name: Henrik Mitsch
    * E-Mail: hmitsch@mozilla.com
    * Bot: No
    * Country: -

Identities:
  0f6da1096c5b9ecba9c45e4637f3af6a2cfa7529      Henrik Mitsch   hmitsch@mozilla.com     hmitsch git
  34fd999b40f451d990a6c74bc4f9c3bcf98c4794      hmitsch hmitsch@mozilla.com     -       mbox
  50c718460755f79bcc8401b498e89dd13701a315      Henrik Mitsch   -       hmitsch remo
  5d79ab65fa02dc168ae7376ceb113729d6cadbf1      Henrik Mitsch [:hmitsch]        hmitsch@mozilla.com     hmitsch@mozilla.com     bugzillarest
  61474813058de31457a90d426d65243ecf75b643      Henrik Mitsch   hmitsch@mozilla.com     hmitsch github
  8a9924d8fbbcb6f64b7b77280755d220282a0251      Henrik Mitsch   -       hmitsch mozillians
  9b3b96afc5af7987adffd37f6f78ab7840b144da      Henrik Mitsch   hmitsch@mozilla.com     hmitsch file:mozillians
  c11a1c2863f47ceb8f4989b6f9306aa011a2f4ae      Henrik Mitsch   -       hmitsch github
  dc232a2af9e5cf5d5e0baa6e4a64a9bc96582ef2      Henrik Mitsch   -       Henrik Mitsch   remo

Enrollments:
  Community     1900-01-01 00:00:00     2100-01-01 00:00:00
  Mozilla Corporation   1900-01-01 00:00:00     2100-01-01 00:00:00

```

Have a look at the identities section, we have the different columns:
* id (a hash)
* name
* email
* source of the information

The process to get unified identites is basically the following:
* we gather data from all the data sources
* extract the accounts we find and store them in a database. 
* Lather, we apply a heuristic in order to match them. 

In this case we've spotted an error with your profile which has two companies assigned. Improving this data will be continuous process and data will be improved during the subscription period as soon as we start diving more and more into the data.

The data is stored in a mariadb database and the tool (https://github.com/MetricsGrimoire/sortinghat) can export everything to json file. We're pretty sure this data will be valuable for you guys.

The process where indexes are enriched use both the ids and the unified id (on top) to feed the enriched indexes, so for instance the file "author_uuid" is common to all the indexes. This is for instance your activity for Git and Reps:
* https://analytics.mozilla.community:443/goto/c0f82076090413cc048065b8c77a8a75
* https://analytics.mozilla.community:443/goto/d30dbb46cb91543f3f3f04bdc1580f69

**Comment by sanacl** [comment]
Can we close this ticket @hmitsch ?
