### ISSUE TITLE
(Deployment) Filter two GitHub bots

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#67]
* B2G Bumper Bot
* bors

**Comment by sanacl** [comment]
Data is updated in our SortingHat database. The blocking task to move this to the enriched data is we don't have that feature with the current software version and indexes we have. I tried to do it with the previous version but it does not make such an effort. 

.. Thus, in order to start moving to the new software (where updating bots, affiliation data and profiles is much much quicker) I've deployed our latest Docker container with fresh software. So a new Git index data is being produced with name "git_mozilla_160801_enriched_161201". 

The limitation here is the Github API rate limitation, even with the cache used by this version I'm not sure whether this will take one day or three :(

**Comment by sanacl** [comment]
New git index produced with updated information about affiliation:
- 1. bots updated
- 2. affiliation about Mozillia staff reviewed (some affiliation errors were found in the old index)
- 3. repository forks removed (some forks like rust-lang/llvm.git)
- 4. this new index was produced following our fresh software, which improves the way we can update affiliation and identities data (basically we can overwrite some fields of the index faster instead of creaaaaaaating a new index which is slow)
I don't want to switch the index until you are aware of this, to avoid misunderstandings. @hmitsch let me know if you are ok with this and I'll move this one to production :)

**Comment by sanacl** [comment]
Index applied. Up & running.

**Comment by hmitsch** [comment]
Closing. Not sure why it was reopened.
