### ISSUE TITLE
Following people's contributions on Github

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#82]
The idea is that based on their github usernames to be able to see all of their contributions in any open github repo (no only ours). Just like the github heatmap we all have in our profile but this time, in bitergia analytics dashboard.
We are want to capture and understand our students interaction with the open source world and understand the impact that our program have in their life.

For example:
I give you a github username and on the dashboard I see all the repositories the user has contributed to in the past years along with some details like number of commits, pull requests etc.

**Comment by bacharakis** [comment]
Thanks @hmitsch ! The description is perfect!
Let me know if you need anything else.

**Comment by jgbarah** [comment]
We're analyzing the GitHub API, and it seems doable. It is not clear yet if the GitHub user should authorize an app (to use a token in their name). I hope to have an answer about that soon.

**Comment by bacharakis** [comment]
Hi there!
Do we have an update on this? Sorry for pinging you again but I would like to have a final projection on this in order to plan accordingly from my side. 
Thank you

**Comment by jgbarah** [comment]
I hope to have a proposal by Wednesday. Some of us are looking carefully at the GitHub Search API, which seems to provide all we need, and then we have to schedule the needed work to provide you with a reasonable time frame.

Do you need this urgently?

**Comment by jgbarah** [comment]
We have been studying the different entry points in GitHub APIs. We have come to a solution that very likely will allow us to produce a dashboard for a certain list of GitHub users, including at least their last contributions (commits, issues, pull requests), in the order of about 1,000 each.

GitHub APIs are very limited in this respect, and that's why the limit on 1,000 contributions, but we're exploring ways of breaking that barrier as well.

In any case, even if it were the last 1,000 contributions of each kind, maybe that would be enough for the kind of analysis you are pursuing.

The solution would imply:

* Adding code to the GitHub Perceval backend to get events related to users from the API (and not only related to repositories, as it does now). For that, we would use the GitHub Search API, and in particular the entry points for issues, pull requests, and commits. It is worth noting that at least the commits entry point is labelled by GitHub as experimental, which could cause some trouble. They have also rate conditions, which could cause trouble in case we need to retrieve events about large lists of users. In any case, from our experiments, up to the last 1,000 events (commits, pull requests or issues) can be retrieved from them. Maybe there are ways of retrieving the full history, which we would explore. These entry points are new for us, since currently Perceval uses other entry points, but we're interested in learning how to use them to their full potential.

* Modifications to GrimoireELK, mainly related to enrichment and production of the Kibana indexes. Those won't be very complex, since the data produced by the Search API is quite similar to the one we're already dealing with. But there are some issues to solve.

* Maybe new panels for Kibiter, to adapt to the new kind of data of interest.

In addition, we would need to deploy a new dashboard for this, and a production environment for the data retrieval and enrichment. But hopefully we could reuse most, if not all, the infrastructure of the current dashboard.

**Comment by hmitsch** [comment]
Mozilla-internal budget discussion is currently happening.

**Comment by canasdiaz** [comment]
@hmitsch our proposal is to use this ticket for the people's contribution on Github, do u agree? We will need to update the description.

**Comment by alpgarcia** [comment]
(@hmitsch if we finally track this in a different ticket I will move this comment there)

Quick update about the external contributions analysis: 

We are a bit late regarding our last estimation. The process is still retrieving information about GitHub issues. Pull Requests are already downloaded and the uuids of Mozilla community people have been also collected. We expect the process to finish in the next hours and start having data by today's evening.

**Comment by alpgarcia** [comment]
@edin-ogtal, @havardl,

we have an initial data set available in Sotrar. After performing some checks to validate the data, we will proceed to build the final index, that will include some extra fields.

Mozilla contributors were selected as all the Git committers that are part of `Community` or `Mozilla Reps`. Their participation in GitHub was in terms of opening Issues and PRs during the last 2 years (2017-01-01 - 2018-12-31). Note that participation in Mozilla repos has not been deleted.

The resulting index contains an entry per contributor and repository with the participation in number of opened issues and number of opened prs.

The index is `github_activity_test`. See an example: https://sotrar.mozilla.community/goto/6468141dfb32948b20ab84cc6a4c639c

**Comment by alpgarcia** [comment]
> Note that participation in Mozilla repos has not been deleted.

For filtering repos, you could use a filter with wildcards like this: https://sotrar.mozilla.community/goto/d069c4e1b6e1af7422acd622c9c74304

**Comment by alpgarcia** [comment]
Update about weekly sync call:
* I've to check with Bitergia's dev team the possibility of adding commits to the index.

**Comment by alpgarcia** [comment]
@havardl, after commenting your question with the team it seems we could retrieve commits with some limitations:

* In order to get the number of commits, we can download push events in addition to PRs and Issues. GitHub API is limited to 20 commits per each push event, so we couldn't retrieve all commits if any push event contained more than 20 commits. 

* We would need some days to get the information ready, but we estimate we could do it in a week from the day we start the retrieval.

* To make things clear, the resulting index would contain two new fields: number of push events and number of commits of a given developer in a specific repo.

If the limitation or the schedule doesn't work for any of you, please let us know. On our side we will start the retrieval as soon we get your confirmation.

**Comment by havardl** [comment]
Thank you for checking @alpgarcia.
@HerminaC - what do you think, I think it's up to you in terms of what data you want to include.

**Comment by HerminaC** [comment]
i don't see an issue with the max of 20 commits/push event - don't think we'll have a lot of cases with more than 20
yes, let's take this approach and see what we get - for sure it can help us get a more complete picture on the contributions

**Comment by edin-ogtal** [comment]
@alpgarcia I have two questions regarind the new index. 
1) `github_activity_test.uuid` does this field refer to the the sortinghat uuid for the user?
2) You mentioned above that this index will contains some extra fields - what extra fields are we talking about, besides the number of push evens and number of commits?

**Comment by alpgarcia** [comment]
@edin-ogtal ,

> @alpgarcia I have two questions regarind the new index.
> 
> 1. `github_activity_test.uuid` does this field refer to the the sortinghat uuid for the user?

Yes, it does.

> 2. You mentioned above that this index will contains some extra fields - what extra fields are we talking about, besides the number of push evens and number of commits?

Sorry about this, I tried to make it clear yesterday during the call. There are some fields we initially defined as part of the index, but probably they are kind of redundant, specifically:
* `organization name`
* `url`

So basically we can add them if you think you are going to need them, but both of them can be obtained from `repository` field.

Apart from those, we already added the ones we thought are enough for cross-referencing data (basically `uuid` and `username` as a backup for checking data). Please, let us know if there is any other field that could help you and we'll have a look.

**Comment by edin-ogtal** [comment]
@alpgarcia 
Thanks. I agree that `organization_name` and `url` are both redundant so don't bother with those.

**Comment by alpgarcia** [comment]
Quick update on the status from yesterday noon:
We're still downloading data of PushEvents. So far, we had completed until 2018-04-13. We have a huge number of events: +150 Millions
(Archives + DB is 300GB).

Code is ready to query the DB and regenerate the index with commits info and updated uuids (given the affiliations changes introduced in sortinghat) once all data is gathered.

**Comment by canasdiaz** [comment]
A new index named `activity_users_20190415` is published with refreshed identities for issues and pull requests. CC @havardl

**Comment by sduenas** [comment]
Sorry with the delay on this. We have generated a new index that contains adds the data about commits: `activity_users_20190421`

On this new index we haven't filtered those repositories which the author is the owner. We didn't do that in the previous indexes either because it's less common to see users opening issues or prs in their own repositories. If they do, probably it's for a good reason and that activity should be taken into account. In the case of commits that's totally normal so maybe it's activity you don't want to consider. We also haven't removed the activity in Mozilla repositories either.

Tell us if you want to remove this kind of activity from the index.

**Comment by canasdiaz** [comment]
@alpgarcia @sduenas can u please what is need to be done here? if we are done please move the ticket to the "Done" column.

**Comment by canasdiaz** [comment]
@havardl I've been talking to my team and we are basically waiting feedback from you. So let us know whether you miss anything in the index.

**Comment by edin-ogtal** [comment]
@sanacl @havardl 
The index seems to be complete, but based on Herminas last comment above it should also contain the number of commits made to a repository. I can't find a field containing this information in the `activity_users_20190421` index.

**Comment by alpgarcia** [comment]
@edin-ogtal not sure what you mean by `number of commits made to a repository`. Each entry contains the number of commits made by the user represented by their `uuid` to a repo:
https://sotrar.mozilla.community/goto/c31af91adbefde80a08e57717ccdcfc5

**Comment by alpgarcia** [comment]
A better view of the index would be something like:
https://sotrar.mozilla.community/goto/d524d33a91b720e766789acd3176740f

**Comment by edin-ogtal** [comment]
@alpgarcia 
Silly me - I've been looking at the `activity_users_20190415` index all along. I wasn't able to see the `activity_users_20190421` index anywhere, but it's there now and contains all the information we need. We can close this issue :)

**Comment by canasdiaz** [comment]
Good news :). MOving to done then :)

**Comment by canasdiaz** [comment]
@hmitsch we are closing this issue :tada:

**Comment by alpgarcia** [comment]
@edin-ogtal I needed to create the index pattern in Kibana, so that's why you didn't see the index there before.

I thought you were directly querying ES as you refer to `activity_users_20190421` in your comment and I didn't see any index pattern for `activity_users_20190421` in Kibana :)
