### ISSUE TITLE
(Prio 0 for Q1/2017) Track a "new technical contributor" metric

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-metrics-org#83]
We have a goal this year of increasing technical contributors to the project. I'd love to create a special visualization for this, if possible.

For now, the query/visualization would be:

- git author
- who has never been a git author in Mozilla repos before
- who is not a Mozilla employee
- displayed as a bar chart by month

So, if there were 120 brand new git authors in Jan 2017, then the bar would show a count of 120.

The total git authors over time would be the summation of all of the monthly bar charts.

**Comment by jgbarah** [comment]
Thanks for the suggestion. We're working on something quite similar. Let us roll it out: we'll keep you informed, and then we can discuss if it is what you need.

**Comment by geroter** [comment]
What's the timeline? I'm hoping to use this for monthly reporting starting ASAP, and need to use it for quarterly reporting starting late March.

Otherwise I need to figure out another way to do this query.

Thanks,
George

**Comment by jgbarah** [comment]
If needed, we can produce the query for you, or just teach how to do it with a Python script directly from live data. In any case, I hope to have it by late March. If you don't need it before, we could sync like in 7-10 days from now, and if it seems it is delayed, revert to the script thing.

**Comment by hmitsch** [comment]
We have two options here:

1. (proper solution) Freeze git index to run the demography analysis and update the panel
2. (fallback solution) Design python queries to extract the information requested in this ticket, directly from the ElasticSearch database

In order to have this ready for Q1 OKR evaluation, the two steps will be done in parallel.

Next check-in with Bitergia (@jgbarah): Monday, 27 MAR 2017, 4.30pm CET.

**Comment by hmitsch** [comment]
Done.
