### ISSUE TITLE
Git Panel: "Number of Authors" and "Names of Authors table" mismatch

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#96]
**Dashboard URL:** https://analytics.mozilla.community:443/goto/28df4a5431ee6e9a9c57a2a2e8e506b6

# Artifacts
<img width="710" alt="image" src="https://cloud.githubusercontent.com/assets/869692/24814913/b454c144-1bd3-11e7-9a8b-175c0fe216bd.png">

* Git Metric: **64 Authors**
* Authors table: **20 Authors**

# Issue
The amount of Authors differ. Strange, right?

**Comment by jgbarah** [comment]
That's because, for performance reasons, the table is limited to show the top 20 authors. I've modified it to 200, so that you can see how now there are much more authors. We don't have tables with long lists because that means more traffic from/to the ElasticSearch server, and more time for the panel to load.

In any case, you will notice that the number of rows in the table now is 62 (with 64 being the number in the metrics widget). That's because, despite how strange it may seem, ElasticSearch calculates unique counts (and the number in the metrics widget is a unique count) only approximately. The degree of approximation can be increased, but again at the cost of less performance (more delay in executing the query).

For most uses this is not really an issue, and the "right" number is the number of rows in the table. But I know it is annoying. If you want, we can adjust to a more strict approximation, and check if performance is good enough. But I would do that only after we have improved the server side (performance of the AWS ElasticSearch instance).

**Comment by hmitsch** [comment]
Abandoned.
